# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

agents:
  queue: "android"

steps:
  - label: "Gradle Wrapper Validation"
    command: |
      validate_gradle_wrapper
    plugins: [$CI_TOOLKIT]

  # Wait for Gradle Wrapper to be validated before running any other jobs
  - wait

  - label: "Lint & Checkstyle"
    key: "lint_and_checkstyle"
    plugins: [$CI_TOOLKIT]
    command: |
      cp gradle.properties-example gradle.properties
      ./gradlew lintRelease checkstyle
    artifact_paths:
      - "**/build/reports/lint-results.*"
      - "**/build/reports/checkstyle/checkstyle.*"
  - label: "Test"
    key: "test"
    plugins: [$CI_TOOLKIT]
    command: |
      cp gradle.properties-example gradle.properties
      ./gradlew testRelease
  # Publish tasks
  - label: "Publish to s3"
    depends_on:
      - "lint_and_checkstyle"
      - "test"
    plugins: [$CI_TOOLKIT]
    command: |
      cp gradle.properties-example gradle.properties
      ./gradlew \
          :WordPressLoginFlow:prepareToPublishToS3 $(prepare_to_publish_to_s3_params) \
          :WordPressLoginFlow:publish
