# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/a8c-ci-toolkit#2.15.0

agents:
  queue: "android"

steps:
  - label: "dependency analysis"
    command: |
      echo "--- 📊 Analyzing"
      cp gradle.properties-example gradle.properties
      ./gradlew buildHealth
    plugins: *common_plugins
    artifact_paths:
      - "build/reports/dependency-analysis/build-health-report.*"
    notify:
      - slack: "#android-core-notifs"
        if: build.state == "failed"
